---
bibliography: [references.bib]
number-sections: true
---

# Introduction:

## What is this PhD about? A quick overview:

This PhD project weaves together multiple threads. The foundational thread of this PhD is rooted in a biological question: understanding the molecular mechanisms underlying memory in animals. To investigate these molecular processes, the project uses computational models to simulate molecular interactions. Experimental studies are increasingly complemented by computational models to aid in characterizing the spatiotemporal regulation of proteins of interest [REFERENCES]. Given the complexity and multiscale nature of biological systems, computational models play a crucial role in integrating experimental data and theoretical hypotheses. Models aim to make clear the current state of knowledge regarding a particular system, by attempting to be precise about the elements involved and the interactions between them. Doing this can be an effective way to highlight gaps in our understanding and guide future research directions.

Moreover, these models then serve to synthesize knowledge from different published research, and make biological predictions which can then serve as hypothesis to be tested empirically by experimentalists. Additionally, computer-simulated experiments can streamline the wet-lab process by narrowing the experimental search space, making research more cost-effective, time-efficient, and environmentally friendly. This approach also promotes ethical research practices by reducing the need for animal testing, thereby minimizing animal suffering.

A major emphasis in this PhD is placed on ensuring these models and the techniques used adhere to the principles of reproducibility and FAIR (Findable, Accessible, Interoperable, Reusable) guidelines. Another critical thread of this research, therefore, involves examining the ethical implications of the work carried out, particularly to identify potential biases and dangers that may be carried on. I use the Data Hazards framework to discuss the ethical implications of this PhD. This framework assigns hazard-like labels, similar to chemical warning labels, to highlight risks such as “danger of misuse” or “high environmental impact.” By doing so, I identify and address relevant ethical risks, implementing or suggesting appropriate safety precautions to mitigate them throughout the research process, from inception to conclusion. 

To provide a more comprehensive overview of this PhD, this introduction chapter will first explore the biological background relevant to the project, including the molecular and cellular mechanisms proposed to underlie memory and learning in animals. Secondly, I will introduce how and why I choose to simulate these molecular mechanisms using computational models. Finally, I will conclude the introduction by briefly discussing how the concept of Data Hazards ties all of it together and encapsulates the entire PhD. 

## Biological Background
### Long Term Potentiaion underlies learning and memory

The cellular changes that underline different forms of memory are thought to involve changes in the strength of neuronal connections. Over a century ago, @ramonycajal1909HistologieSystemeNerveux proposed that the nervous system is composed of microscopic, independent cells —neurons— that form intricate networks of connections. The notion that synaptic strength changes during learning and memory was refined into a concrete model by @hebb1949OrganizationBehaviorNeuropsychological. Hebb proposed that if two neurons are active at the same time, the synapses between them are strengthened. The first mechanism supporting synaptic strengthening, long-term potentiation (LTP), was then discovered in the late 1960s using rabbits' hippocampus _in vitro_. This discovery of LTP showed that short, high frequency stimulation (tetanus) of hippocampal excitatory synapses produced a rapid and long-lasting increase in the strength of these synapses that could persist for many days [LOMO Gardner-Medwin REFERENCE]. 

In 1986, Morris et al. provided some of the first evidence that LTP was indeed required for the formation of memories _in vivo_ using rats. These rats were trained in the Morris water maze, a spatial memory task in which the rodents swam in a pool of murky water until they located a platform hidden beneath the surface. During this exercise, the rats had no other choice but to learn the location of the hidden platform through salient cues placed at specific positions around the maze's circumference. After the rats had memorised where the cues and platforms were, one group was subjected to having their hippocampi bathed in the NMDA receptor blocker APV, while another group to whom nothing was done to, served as the control. Rats in the control group were able to locate the platform and escape from the pool. However, the rats that had been subjected to APV treatment had significantly impaired memory. Moreover, when both groups were killed and slices of their hippocampal slices were analyzed, LTP was readily induced in the control group, while it could not be induced in the brains of the rats subjected to APV treatment. This experiment using rats provided early evidence that the NMDA receptor — and by extension, LTP — was required for at least some types of learning and memory. In the years since, there have been many more experiments conducted on rodents, often using fear conditioning or subjecting them to brain injuries, that provide further evidence of LTP's role in different types of memory and learning [REFERENCES].

Since its discovery, different forms of LTP have been observed throughout different regions in the brain, in human and non-human animals [REFERENCES]. What is more, the different forms of LTP further depend on a number of factors such as developmental stage, pre- or post-synaptic stimulation as well as stimulation protocols. Two major types of LTP have been described as being either NMDA receptor-dependent or NMDA receptor-independent [REFERENCES @kumar2011LongTerm (Grover and Teyler, 1992; Cavus and Teyler, 1996)]. For example, LTP induced at the CA3–CA1 hippocampal synapses employing high-frequency stimulation has been shown to be dependent on the NMDA receptor (Collingridge et al., 1983; Harris et al., 1984; Morris et al., 1986), whereas at the same synapses, an NMDA-independent form of LTP can be induced by using a 200-Hz stimulation protocol [@grover1990Two; @grover1998Evidence], among other stimulation protocols [@aou2003Orexinhypocretin1; @rebola2008Adenosine; @erondu1985RegionalDistributionType; @bortolotto1999Roles; @zi1993Induction; @bortolotto1993Characterisation]. Similarly, LTP at CA1 synapses, which can be representative of LTP at excitatory synapses, is dependent on NMDA receptor activation and primarily involves a modification of the postsynaptic neuron. Mossy fibre LTP at CA3 pyramidal cells, on the other hand, is independent of NMDA receptors and has been shown to be entirely expressed presynaptically (Nicoll and Schmitz, 2005). This project will focus on studying the NMDA receptor-dependent form of LTP at synapses in the CA1 region of the hippocampus. To avoid ambiguities, this is the type of LTP discussed unless otherwise stated. 

LTP is usually divided into two main phases: early (E-LTP) and late LTP (L-LTP), although an initial/short sterm potentiation and an intermidiate phase of LTP have also been suggested [REFERENCES]. E-LTP occurs shortly after high-frequency stimulation of a synapse, and is typically characterized by a rapid increase in synaptic strength that lasts for a few minutes to hours [REFERENCES]. It relies primarily on the activation of NMDA receptors and the influx of calcium ions. L-LTP, on the other hand, is the prolonged phase of synaptic enhancement that can last for days or even weeks. L-LTP is dependent on new protein synthesis and gene expression. This phase is critical for the consolidation of memory and is associated with structural changes in the synapse, including the growth of dendritic spines and the synthesis of new receptors. Within these phases, LTP is also often divided into three main events: induction, expression, and maintenance [REFERENCES]. _Induction_ refers to the transient events that initiate the formation of LTP. _Maintenance_ refers to a persisting biochemical signal that lasts in the neurons [@sweatt2010Chaptera]. This lasting biochemical signal influences an effector, such as a glutamate receptor like NMDARs, leading to the _expression_ of LTP.

These three events are not rigidly defined as sequential phases of LTP; rather, they serve as distinct categories to help us talk about the different stages of LTP. Induction, expression, and maintenance can apply to both E-LTP and L-LTP; with E-LTP and L-LTP phases being _induced_ and _expressed_ in diverse ways (for example, either through protein synthesis or not) and _maintained_ for differing durations (for seconds, hours or longer). Additionally, E-LTP and L-LTP are not mutually exclusive. In fact, depending on the specific LTP induction protocol applied, E-LTP can happen concurrently with the development of L-LTP, with one gradually replacing the other over time [@roberson1996Biochemists]. This PhD research focuses on the role of specific molecular interactions that happen during E-LTP induction and maintenance, as discussed in the following sections.

### LTP as an attractive model to explain memory at the cellular and molecular level

To this day, LTP remains an attractive model to explain memory at the cellular and molecular level due to some of its properties. These properties include the principles of associativity, cooperativity, input-specificity, and persistence. The associativity principle indicates that a weak tetanic stimulation that activates only a few fibers does not induce LTP. However, simultaneous strong stimulation of a neighboring pathway can induce LTP in both synaptic pathways (Levy and Steward, 1979). Cooperativity can be observed when a weak stimulation is paired with a strong postsynaptic depolarization. In this case, LTP is induced only if the postsynaptic cell is depolarized within approximately 100ms of neurotransmitter release from the presynaptic cell. Input-specificity stipulates that LTP occurs only in the synaptic pathway that received the tetanic stimulation, whilst inactive synapses that contact the same neuron will not share synaptic enhancement (Andersen et al., 1977; Lynch et al., 1977). Together, these characteristics set conditional requirements that are likely to allow selective strengthening of specific synaptic connections thought to be involved in memory storage. In regards to persistence, LTP has been shown to last for several hours in _in vitro_ slice preparations and for many months in freely moving animals (in vivo; Abraham, 2003), suggesting a capacity for sustained physiological changes that aligns well with memory formation. 

#### Cellular and molecular mechanisms in LTP

There are multiple molecular and cellular mechanisms that contribute to induction, expression, and maintenance of LTP. E-LTP is induced when the intracellular calcium concentration in the postsynaptic cell rises above a critical threshold. The influx of Ca²⁺ into the cell is facilitated by NMDA receptors, which are ionotropic, non-selective cationic glutamate receptors essential for the rapid regulation of synaptic plasticity. The activation of the NMDA receptor is regulated by a voltage-dependent magnesium (Mg++) block within the channel's pore. For the Mg++ ion to be expelled from the pore, membrane depolarization is required. Once this occurs, calcium ions can pass through it. As a result, these receptors act as molecular coincidence detectors, allowing ion flux only when these conditions are met. This is a critical aspect of NMDA receptor regulation, enabling the receptor to play a unique role in molecular-level information processing.

Tetanic stimulation of presynaptic fibers leads to the release of neurotransmitters, mainly glutamate, onto the membrane of the postsynaptic cell. Glutamate binding to postsynaptic α-amino-3-hydroxy-5-methyl-4-isoxazolepropionic acid (AMPA) receptors triggers an influx of positively charged sodium ions into the postsynaptic cell, leading to cell depolarization. The magnitude of depolarization determines the amount of Ca2+ entry into the postsynaptic cell. If the degree of depolarization is sufficient to remove the Mg2+ block of the NMDA receptor as mentioned before, then the channel will allow influx of Ca2+ into the cell. This influx then leads to an increase in intracellular calcium concentrations within the postsynaptic density (PSD) of dendritic spines, which are specialized protrusions on neurons that serve as the primary sites for excitatory synaptic transmission. Following the entry of calcium, the ions can bind to calmodulin (CaM) to form a Ca2+/CaM complex that is recognized by multiple enzymes. Calcium/calmodulin-dependent protein kinase II (CaMKII) is one of the primary targets of the Ca²⁺/CaM complex. This interaction triggers a molecular signaling cascade that ultimately induces reshaping of the synaptic strcuture and physiology, as well as regulating gene expression essential for memory formation. 

CaMKII is expressed ubiquitously in animals; there are four known isoforms $\alpha$, $\beta$, $\gamma$ and $\lambda$ [REFERENCES]. This study focuses on the brain specific $\alpha$ isoform, which constitutes up to 2% of total brain protein. $\alpha$-CaMKII is one of the main proteins in the PSD, and has extensively been shown to be important for LTP and memory formation [REFERENCES]. Unless otherwise stated, references to CaMKII throughout this project will specifically pertain to $\alpha$-CaMKII. This kinase is a large holoenzyme consisting of 10/12 subunits [REFERENCES]. Each of the subunits has a catalytic/kinase domain, followed by a regulatory domain that contains a self-inhibitory region and a binding site for the Ca2+/calmodulin (CaM) complex [FIGURE]. At its basal state, CaMKII is found with its subunits mostly in their closed, inactive state where the regulatory domain is bound to the kinase domain [FIGURE]. In the open conformation, CaMKII subunits can autophosphorylate each other at threonine 286 (T286) found in the inhibitory segment, which prevents the segment from closing, and uncovers the binding sites in the kinase domain for CaMKIIs substrates and anchoring proteins. This autophosphorylation event allows CaMKII to remain in an autonomous, calcium/calmodulin-independent active form, which permits activity to persist even after the initial calcium stimulus has passed [REFERENCES]. In fact, one of the most popular theories for memory in molecular neuroscience has been that LTP induction (and potentially maintenance) requires enzymatic activity of CaMKII [REFERENCES]. The enzymatic action of CaMKII has two types of targets, first, itself, as autophosphorylation maintains the enzyme in the open, active, and autonomous, conformation. Secondly, CaMKIIs enzymatic action also targets the phosphorylation of various downstream target proteins, such as the GluA1 subunit of AMPARs, or the GluN2B subunit of NMDARs. 

The T286 autophosphorylation mechanism of CaMKII has long been proposed as a critical requirement for LTP induction. Interestingly, studies using pharmacological and optogenetic inhibitors of CaMKII have demonstrated that blocking CaMKII activity before LTP induction abolishes LTP, but inhibiting CaMKII after LTP induction does not reverse LTP, which is inconsistent with the autonomous CaMKII hypothesis of biochemical memory storage _(Buard et al., 2010; Chen et al., 2001; Malinow et al., 1989; Murakoshi et al., 2017; Otmakhov et al., 1997; Sanhueza et al., 2011), but also see (Sanhueza et al., 2007).https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5573161/._ The relative significance of CaMKIIs T286 autophosphorylation, phosphorylation and binding of downstream target proteins, continues to be a subject of intense debate [REFERENCES]. Much of the uncertainty in interpreting studies that inhibit CaMKII enzymatic activity and its exact role in LTP arises from the fact that such inhibition also disrupts CaMKII's structural functions, particularly its binding to the GluN2B subunit of NMDA receptors. 

There is increasing evidence supporting a structural model in which LTP is maintained through the binding of CaMKII to the GluN2B subunit, independent of CaMKII's enzymatic activity. Very recently, there have been some key studies [REFERENCES] that focused on finding the minimal requirements for the ability of CaMKII to enhance synaptic transmission and its role in LTP maintenance. Although these studies were conducted independently, they both arrived at a similar conclusion: the role of T286 phosphorylation in CaMKII during LTP may not be primarily enzymatic. Instead, it may serve to enable and stabilize the CaMKII/GluN2B complex that is _essential_ for regulating synaptic CaMKII accumulation and supporting the associated structural functions of CaMKII required for LTP. In other words, T286 phosphorylation is involved in the initial signal processing that triggers LTP induction, enabling a downstream response via CaMKII's structural functions without requiring enzymatic activity. It is these structural functions of CaMKII that are, therefore, more likely to meet the essential and minimum molecular requirements for LTP induction and maintenance, though the precise mechanisms remain unclear. The CaMKII/NMDAR complex may enable activity-dependent CaMKII incorporation into postsynaptic sites, potentially acting as a structural seed to recruit postsynaptic density proteins, contributing to synapse restructuring and plasticity. 

Ultimately, any structural LTP mechanism must regulate the filamentous (F)-actin cytoskeleton in dendritic spines, as changes in spine shape and size are closely linked to actin remodelling, which affects the strength of excitatory synaptic connections. During LTP induction, the balance between F-actin polymerization and degradation is transiently altered. Emerging evidence indicates that most signalling pathways linking synaptic activity to spine morphology modulate local actin dynamics.  Dendritic spine morphogenesis involves many actin-binding proteins and signaling pathways, which are beyond the scope of this project. However, our protein of interest, CaMKII, is situated upstream of the signalling pathway leading to F-actin modification [REFERENCES]. Notably, the $\beta$-CaMKII isoform has been shown to have direct structural roles in binding and bundling F-actin filaments [REFERENCES]. In its inactive, closed conformation, the $\beta$-CaMKII isoform is is bound to and crosslinked with F-actin filaments via the variable linker between the regulatory and association domains. This limits access of actin-regulating proteins to F-actin and stabilizes spine structure. Upon calcium influx through NMDARs after postsynaptic stimulation, after $\alpha$-CaMKII becomes autophosphorylayted, it can translocate from the PSD to interact with $\beta$-CaMKII, eventually leading to autophosphorylation of T287 in the latter isoform. This autophosphorylation releases $\beta$-CaMKII from F-actin, enabling actin remodelling via other actin regulators [REFERENCE]. Its subsequent reassociation stabilises the restructured F-actin for extended periods of time [REFERENCE]. Thus, the activity-dependent dissociation of $\beta$-CaMKII from F-actin may be of importace for actin dynamics remodelling that may allow dendritic spine plasticity and synaptic reorganization during LTP [REFERENCES]. It has been demonstrated that both $\alpha$ and $\beta$ isoforms of CaMKII can directly interact with the GluN2B subunit of NMDARs. However,  it is the $\alpha$ isoform, rather than the $\beta$, that is proposed to facilitate the activity-dependent incorporation of the CaMKII/NMDAR complex into postsynaptic sites [REFERENCES https://pubmed.ncbi.nlm.nih.gov/12873385/]. This process may act as a structural scaffold, recruiting postsynaptic density proteins and contributing to synaptic restructuring and plasticity. Consequently, these two primary neuronal isoforms appear to have distinct roles in neuronal plasticity, with $\alpha$ CaMKII regulating synaptic strength and $\beta$-CaMKII influencing dendritic morphology.

CaMKII and NMDAR binding has been shown to play a critical role in maintaining LTP [REFERENCE], yet the duration of this complex after LTP induction remains unclear (REFERENCES NEED TO LOOK THIS UP GOOD TO TEST). What is more, the precise mechanism of how CaMKII and NMDAR interactions form a complex is also hotly debated.A longstanding model posited that CaMKII binds to two distinct sites on the NMDAR C-terminal [REFERENCES]. However, recent crystal structure studies challenge this by suggesting that CaMKII substrates and activators interact at a single continuous site on the kinase domain [REFERENCE]. These findings underscore the importance of further research into the dynamics of CaMKII/NMDAR interactions. Gaining a clearer understanding of these interactions may shed light on the biochemical processes that stabilise memories and provide crucial insights into LTP and memory formation. Therefore, this PhD research of relevance and is well positioned to allow us to test the minimal requirements of CaMKII/NMDAR interactions while considering the spatial and temporal dynamics of CaMKII activity using computer models of these interactions.

--.

CaMKII and NMDAR binding complex has been shown to maintain LTP [REFERENCE], it is not yet known how long this complex lasts after LTP induction (REFERENCES NEED TO LOOK THIS UP GOOD TO TEST). What is more, the precise mechanism of how CaMKII and NMDAR interactions form a complex is also hotly debated. A longstanding model suggested CaMKII has two distinct sites that bind to the NMDAR C-terminal [REFERENCES]. However, recent crystal structure studies challenge this, showing that CaMKII substrates and activators bind to a single continuous site across the kinase domain [REFERENCE]. Taken together, all of this knowledge (or lack thereof) highlights the need for further research into the CaMKII/NMDAR interactions, as understanding these dynamics is important as it may provide insights into the biochemical processes that stabilize memories and contribute to our overall understanding of LTP and memory formation. _This is why this research is important - we are able to test for minimal requirements of CaMKII/NMDAR interactions taking into account spatial and time dynamics of CaMKII activity._

--

Ultimately, any structural LTP mechanism must regulate the filamentous (F)-actin cytoskeleton in dendritic spines, as changes in spine shape and size are closely linked to actin remodelling, which affects the strength of excitatory synaptic connections. During LTP induction, the balance between F-actin polymerization and degradation is transiently altered. Emerging evidence indicates that most signalling pathways linking synaptic activity to spine morphology modulate local actin dynamics.  Dendritic spine morphogenesis involves many actin-binding proteins and signaling pathways, which are beyond the scope of this project. However, our protein of interest, CaMKII, is situated upstream of the signalling pathway leading to F-actin modification [REFERENCES]. Notably, the $\beta$-CaMKII isoform has been shown to have direct structural roles in binding and bundling F-actin filaments [REFERENCES]. In its inactive, closed conformation, the $\beta$-CaMKII isoform is is bound to and crosslinked with F-actin filaments via the variable linker between the regulatory and association domains. This limits access of actin-regulating proteins to F-actin and stabilizes spine structure. Upon calcium influx through NMDARs after postsynaptic stimulation, after $\alpha$-CaMKII becomes autophosphorylayted, it can translocate from the PSD to interact with $\beta$-CaMKII, eventually leading to autophosphorylation of T287 in the latter isoform. This autophosphorylation releases $\beta$-CaMKII from F-actin, enabling actin remodelling via other actin regulators [REFERENCE]. Its subsequent reassociation stabilises the restructured F-actin for extended periods of time [REFERENCE]. Thus, the activity-dependent dissociation of $\beta$-CaMKII from F-actin may be of importace for actin dynamics remodelling that may allow dendritic spine plasticity and synaptic reorganization during LTP [REFERENCES]. It has been shown that both alpha and beta CaMKII can directly interact with the GluN2B subunit of NMDARs, and it has been proposed that it is the alpha isoform, not the beta, that enables the CaMKII/NMDAR complex activity-dependent CaMKII incorporation into postsynaptic sites, potentially acting as a structural seed to recruit postsynaptic density proteins, contributing to synapse restructuring and plasticity. These two main neuronal CaMKII isoforms may therefore have markedly different roles in neuronal plasticity, with CaMKIIalpha regulating synaptic strength and CaMKIIbeta controlling the dendritic morphology and number of synapses [https://pubmed.ncbi.nlm.nih.gov/12873385/].

Although CaMKII and NMDAR binding complex has been shown to maintain LTP [REFERENCE], it is not yet known how long this complex lasts after LTP induction (REFERENCES NEED TO LOOK THIS UP GOOD TO TEST). What is more, the precise mechanism of how CaMKII and NMDAR interactions form a complex is also hotly debated. A longstanding model suggested CaMKII has two distinct sites that bind to the NMDAR C-terminal [REFERENCES]. However, recent crystal structure studies challenge this, showing that CaMKII substrates and activators bind to a single continuous site across the kinase domain [REFERENCE]. Taken together, all of this knowledge (or lack thereof) highlights the need for further research into the CaMKII/NMDAR interactions, as understanding these dynamics is important as it may provide insights into the biochemical processes that stabilize memories and contribute to our overall understanding of LTP and memory formation. _This is why this research is important - we are able to test for minimal requirements of CaMKII/NMDAR interactions taking into account spatial and time dynamics of CaMKII activity._

Ultimately, any structural LTP mechanism must regulate the filamentous (F)-actin cytoskeleton in dendritic spines, as changes in spine shape and size are closely linked to actin remodelling, which affects the strength of excitatory synaptic connections. During LTP induction, the balance between F-actin polymerization and degradation is transiently altered. Emerging evidence indicates that most signalling pathways linking synaptic activity to spine morphology modulate local actin dynamics. Actin undergoes continuous treadmilling from the periphery to the center of the spine head, maintaining spine structure (Honkura et al., 2008; Frost et al., 2010). Dendritic spine morphogenesis involves many actin-binding proteins and signaling pathways, which are beyond the scope of this project. However, our protein of interest, CaMKII, is situated upstream of the signalling pathway leading to F-actin modification [REFERENCES]. Notably, the $\beta$-CaMKII isoform has been shown to have direct structural roles in binding and bundling F-actin filaments [REFERENCES]. In its inactive, closed conformation, the $\beta$-CaMKII isoform is is bound to and crosslinked with F-actin filaments via the variable linker between the regulatory and association domains. F-actin binding targets CaMKII dodecamers to dendritic spines, where F-actin is concentrated. This limits access of actin-regulating proteins to F-actin and stabilizes spine structure. Upon calcium influx through NMDARs after postsynaptic stimulation, a cascade of events —which remains to be ellucidated— is thought to allow $\alpha$-CaMKII subunits in the PSD to interact with $\beta$-CaMKII, eventually leading to autophosphorylation of T287 in the latter isoform. This autophosphorylation releases $\beta$-CaMKII from F-actin, enabling actin remodelling via other actin regulators [REFERENCE]. Its subsequent reassociation stabilises the restructured F-actin for extended periods of time [REFERENCE]. Thus, the activity-dependent dissociation of $\beta$-CaMKII from F-actin may be of importace for actin dynamics remodelling that may allow dendritic spine plasticity and synaptic reorganization during LTP [REFERENCES]. That being said, recent studies using CRISPR-based system to delete CaMKII and replace it with mutated forms in single neurons, showed that basal AMPAR and NMDAR synaptic transmission both require $\alpha$-CaMKII, but not $\beta$-CaMKII. This indicates that the $\alpha$-CaMKII isoform actions that may be involved in essential requirements for synaptic transmission [https://www.nature.com/articles/s41467-018-04439-7].



Interestingly, binding of CaMKII to F-actin versus GluN2B seem to be oppositely regulated, 

 CaMKII binding to GluN2B has been described to increase binding of the CaMKII regulatory domain to α-actinin-2,79

These results show that the two main neuronal CaMKII isoforms have markedly different roles in neuronal plasticity, with CaMKIIalpha regulating synaptic strength and CaMKIIbeta controlling the dendritic morphology and number of synapses.https://pubmed.ncbi.nlm.nih.gov/12873385/

with activating signals disrupting the F-actin binding rather than inducing it.

--
Notably, the $\beta$-CaMKII isoform has been shown to have direct F-actin binding and bundling structural functions [REFERENCES]. $\beta$-CaMKII is found to be bound to and crosslinked with F-actin filaments via the variable linker between the regulatory and association domains of CaMKIIβ, which is different from $\alpha$-CaMKII. F-actin binding targets CaMKII dodecamers to spines, where F-actin is concentrated. Upon calcium influx through NMDARs, through a cascase of events that is yet to be fully understood, $\alpha$-CaMKII subunits the PSD can interact with $\beta$-CaMKII and potentially lead to autophosphorylate at T287 of the latter isoform, although this is not yet fully understood. This causes it to detach from F-actin and is proposed to open a brief time window for actin remodelling. Reassociation of this CaMKII isoform with F-actin closes the time window and stabilizes the new F-actin structure for extended periods of time [REFERENCE].

--

Ultimately, any structural LTP mechanism has to regulate the filamentous (F)-actin cytoskeleton component in dendritic spines. During LTP induction, the balance between F-actin formation and degradation is transiently shifted. Emerging evidence suggests that most signaling pathways linking synaptic activity to spine morphology influence local actin dynamics. Actin undergoes constant treadmilling from the periphery toward the center of the spine head, maintaining the structure of each spine (Honkura et al., 2008, Frost et al., 2010). And Changes in the shape and size of dendritic spines are correlated with the strength of excitatory synaptic connections and heavily depend on remodeling of its underlying actin cytoskeleton. 

Ultimately, structural LTP mechanisms are likely to relate to cytoskeletal components in dendrites.  Changes in the shape and size of dendritic spines are correlated with the strength of excitatory synaptic connections and heavily depend on remodeling of its underlying actin cytoskeleton. Emerging evidence suggests that most signaling pathways linking synaptic activity to spine morphology influence local actin dynamics. Actin undergoes constant treadmilling from the periphery toward the center of the spine head, maintaining the structure of each spine (Honkura et al., 2008, Frost et al., 2010).  During LTP induction, the balance between filamentous (F-) actin formation and degradation is transiently shifted. LTP is characterized by a shift to new, elevated steady-state levels of F-actin content, which persistently supports the enlarged spine structure (Okamoto et al., 2004, Bosch et al., 2014). Therefore, during LTP induction, F-actin undergoes a biphasic reaction characterized by an initial reorganization, followed by a restabilization phase.

CaMKII is situated upstream of the signaling leading to F-actin modification and contributes to synaptic plasticity through kinase-dependent and independent, structural functions.  The autophosphorylation of CaMKII detaches it from F-actin and thereby opens a brief time window for actin remodeling. Reassociation of CaMKII with F-actin closes the time window and stabilizes the new F-actin structure for extended periods of time. In light of these findings, we propose that CaMKII serves as a general inhibitor of F-actin remodeling in spines, whose activity is negatively regulated by Ca2+/calmodulin (CaM) binding and by the resultant autophosphorylation within a limited time period after LTP induction.


Glutamate postsynaptic stimulation induces CaMKIIβ/F-actin release and subsequent PSD localization. The dissociation process requires binding of Ca2+/CaM to CaMKIIβ and/or autophosphorylation at T287 and is not dependant on CaMKIIβ kinase activity (Shen and Meyer, 1999; Lin and Redmond, 2008).
--

An important trigger for LTP is the influx of Ca2+ through the NMDA-R and the resultant activation of CaMKII. 

The actin cytoskeleton is known to play a pivotal role in regulating spine shape


During LTP of hippocampal CA1 pyramidal cells dendritic spines have been shown to expand within 60s after LTP induction. 

--
_Ultimately, any structural LTP mechanism has to regulate the F-actin cytoskeleton. However, even though direct F-actin binding and bundling are among the structural functions of CaMKII, this is largely restricted to the CaMKIIß isoform rather than the major α isoform studied here. @tullis2023LTP_ CaMKIIβ binds to and crosslinks F-actin filaments.  F-actin binding targets CaMKII dodecamers to spines, where F-actin is concentrated. Upon Ca2+ influx, Ca2+/CaM and T287 autophosphorylation displace CaMKIIβ from F-actin (Lin and Redmond, 2008, Shen and Meyer, 1999) (Figure 3). Notably, CaMKIIβ has an ∼9-fold higher affinity for Ca2+/CaM (EC50 for autophosphorylation: 15 nM) than CaMKIIα (Brocke et al., 1999), suggesting that CaMKIIβ-containing dodecamers are readily released from F-actin before CaMKIIα subunits bind Ca2+/CaM and are activated. However, Ca2+/CaM binding to CaMKIIα is necessary for T287 phosphorylation of CaMKIIβ in native forebrain dodecamers as CaMKIIα subunits phosphorylate CaMKIIβ subunits (Brocke et al., 1999). https://www.sciencedirect.com/science/article/pii/S0896627313011859

mention camkii binds to other subtstrates like densin, neurogranin, too but it is not the focus here as it seems nmdar/camkii complex may be the minmum requirement - although i dont erally know about densin or neurogranin. might be wroth reading a bit more on this see what literature says. the paper that sasy camkii only binds substrates on kinase site says explictly which binding subtrates of camkii are known - look at that and maybe reference. 

Another well-known CaMKII substrate site is S831 (and, to a lesser extent, S845) on the C-terminal domain (CTD) of the AMPAR subunit GluA1. CaMKII phosphorylation of S831 in GluA1 increases AMPAR single-channel conductance, enhancing sodium ion flow into the postsynaptic neuron upon glutamate activation. This enhanced conductance of AMPARs can also result in a larger excitatory postsynaptic current (EPSC), which strengthens synaptic connections. The greater influx of sodium ions through phosphorylated AMPARs can lead to a more substantial depolarization of the postsynaptic membrane. This depolarization can facilitate further calcium entry through NMDA receptors (NMDARs), which is critical for LTP induction as dicussed above. By increasing the activity and efficiency of AMPARs, CaMKII-mediated phosphorylation of the GluA1 subunit can help stabilize synaptic changes over time. It is also proposed that $\alpha$ and $\beta$ CaMKII isoforms activation and their postsynaptic translocation induces the synaptic trapping of AMPARs diffusing in the membrane, although the exact mechanisms remain unclear [@diaz-alonsoLongterm; @opazo2010CaMKII; @patriarchi2018Postsynaptic; @hell2014CaMKII]. Notably, while CaMKII phosphorylation of GluA1 is important for mediating LTP mechanisms, strong evidence suggests that this may not be essential for LTP. LTP could still be observed _in vivo_ in knock-in mice lacking the CTD of GluA1 subunit in AMPA receptors. Additionally, as LTP was also observed _in vitro_ when the GluA1 C-tail was transfected in mouse CA1 hippocampal pyramidal neurons. Instead, what may be necessary is a reserve pool of glutamate receptors independent of subunit type [@lee2010Specific; @diaz-alonsoLongterm; @granger2013LTP]. 

-link with CaMKII/nmdar complex duration. -> and why this PhD IS IMPORTANT - YAY! GOOD LINKING.

Importantly, CaMKII and NMDAR binding has been shown to maintain LTP [REFERENCE]; however, the exact mechanisms behind this remain unclear. We don't know how long the CaMKII/NMDAR complex lasts after LTP induction (REFERENCES NEED TO LOOK THIS UP GOOD TO TEST) and more work is also required to elucidate how the CaMKII/NMDAR complex produces the structural growth of the synapse that underlies late LTP. What is more, the precise mechanism of CaMKII and NMDAR interaction to form a complex remains unclear. A longstanding model suggested CaMKII has two distinct sites that bind to the NMDAR C-terminal [REFERENCES]. However, recent crystal structure studies challenge this, showing that CaMKII substrates and activators bind to a single continuous site across the kinase domain [REFERENCE]. The CaMKII/NMDAR complex enables activity-dependent CaMKII incorporation into postsynaptic sites, potentially acting as a structural seed to recruit postsynaptic density proteins, contributing to synapse restructuring and plasticity. 

The specific mechanisms through which the CaMKII/NMDAR complex sustains LTP and facilitates synaptic restructuring remain poorly understood, highlighting the need for further research into their interactions. Understanding these dynamics is important as it may provide insights into the biochemical processes that stabilize memories and contribute to our overall understanding of LTP and memory formation.

CaMKII other functions - queue hosphorylation of ampar glua1, and actin functions. 

Thus, generation of pT286 is part of the initial upstream signal processing that leads to LTP induction, which enables the downstream output through the structural functions of CaMKII without any requirement for enzymatic activity toward exogenous substrates.

Thus, generation of pT286 is part of the initial upstream signal processing that leads to LTP induction, which enables the downstream output through the structural functions of CaMKII without any requirement for enzymatic activity toward exogenous substrates.

Although these studies were done separately, both reach a similar conclusion: the role of T286 phosphorylation in CaMKII in LTP may not be for the generation of the Ca2+-independent ‘autonomous’ activity, but instead, to enable and stabilizing the CaMKII/GluN2B complex for the required regulation of synaptic CaMKII accumulation and the coinciding structural CaMKII functions.



--


This high and rapid rise in intracellular calcium then triggers a cascade of events, including activation of several kinases, such as calcium-calmodulin-dependent kinase II (CaMKII). 

CaMKII is expressed ubiquitously through the body and there are four known isoforms $\alpha$, $\beta$, $\gamma$ and $\lambda$ [REFERENCES]. This study focuses on the brain specific $\alpha$ isoforms, which constitute up to 2% of total brain protein. $\alpha$-CaMKII is one of the main proteins in the postsynaptic density (PSD) of dendrites, and has extensively been shown to be important for LTP and memory formation [REFERENCES]. We also discuss the $\beta$-CaMKII isoform and its high-affinity binding to F-actin filaments in postsynaptic dendrites. Unless otherwise stated, references to CaMKII throughout will specifically pertain to $\alpha$-CaMKII.

--
the only required kinase role of CaMKII in LTP is its autophosphorylation of T286, which, by enabling and stabilizing the CaMKII/GluN2B complex, maintains synaptic memory independent of phosphorylation of downstream targets.

However, according to our results, the function of pT286 in LTP is not for the generation of the Ca2+-independent ‘autonomous’ activity15,16 as generally proposed1–3 but instead, to enable the required regulation of synaptic CaMKII accumulation and the coinciding structural CaMKII functions.

these studies propose that CaMKII autophosphorylation 


In the structural scenario, LTP is maintained by the binding of CaMKII to GluN2B independent of any enzymatic activity, either of itself or toward target proteins.

--
 _Biochemical studies indicate that CaMKII catalyzes a phosphotransferase (kinase) reaction of both itself (autophosphorylation) and of multiple downstream target proteins._

One of the most popular theories for memory in molecular neuroscience has been that LTP induction requires enzymatic activity of CaMKII. 

The T286 autophosphorylation of CaMKII has been proposed as a critical requirement for LTP induction, as inhibition of this modification has been shown to block LTP. While there is broad consensus that CaMKII is necessary for LTP induction, there are ongoing discussions about whether it is also necessary or modulatory but dispensable for the maintenance of LTP. Additionally, Recent findings by Tullis et al. (2023) propose that the role of CaMKII in LTP maintenance may be more structurally than enzymatically driven. Specifically, they suggest that CaMKII's involvement in LTP induction is not necessarily dependent on its autophosphorylation or the phosphorylation of other substrates. Instead, they propose that CaMKII’s role in LTP is linked to its structural interaction with NMDARs.

CaMKIIs autonomous activity and auophosphorylation have been proposed as a critical requirement for LTP induction, as inhibition of this autophosphorylation in the kinase has been shown to block the induction of LTP (is this enough argument? what else would show it to be necessary not just part of the process?). However, CaMKII inhibition has not been shown to prevent LTP maintenance. Although most literature points to CaMKII being necessary for induction, and a mediator in maintenance, there is still debate about it, as there have been studies that propose CaMKII as being necessary for maintenance too. A lot of these discussions focus around CaMKII's functions being "modulating" vs "necessary". A lot fot the time these discussions happen because we think phosphhorylation does one thing but its not. Recently, Tullis et al., 2023 have proposed that CaMKII function during LTP is due to its structural functions rather than enzymatic, i.e. regardless of its autophosphorylation or [hosphorylation of other substrates.] Instead they propose CaMKIIs role in LTP induction is directly related to its binding to NMDARs. 

_While CaMKII is required for long-term potentiation (LTP), a compelling cellular model for learning and memory, the role of kinase activity in its synaptic actions is hotly debated._ https://www.pnas.org/doi/10.1073/pnas.2402783121

_Consistent with the critical role Thr286 phosphorylation in LTP, knock-in mice in which Thr286 of CaMKIIα is mutated to Alanine (Camk2aT286A) were impaired in LTP, learning and memory (Giese et al., 1998). However, it was found that the memory deficits in Camk2aT286A mice can be overcome by intense training, suggesting that the phosphorylation may be not required for the maintenance of memory once it is established (Irvine et al., 2005). Furthermore, studies using pharmacological or optogenetic inhibitors of CaMKII demonstrated that blocking CaMKII activity before LTP induction abolishes LTP, but inhibiting CaMKII after LTP induction does not reverse LTP, inconsistent with the autonomous CaMKII hypothesis of biochemical memory storage (Buard et al., 2010; Chen et al., 2001; Malinow et al., 1989; Murakoshi et al., 2017; Otmakhov et al., 1997; Sanhueza et al., 2011), but also see (Sanhueza et al., 2007)._ https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5573161/

_The imaging results showed that CaMKII activation rapidly occurs in ~10 s and returns to basal levels within ~1 min during sLTP, suggesting that CaMKII activation is transient (Lee et al., 2009; Yagishita et al., 2014). However, the exact role of Thr286 phosphorylation in CaMKII activation during spine plasticity still remains elusive._

_T286-phosphorylation has been described as a form of molecular memory, and is indeed required for normal learning and memory, as well as for two opposing forms of synaptic plasticity, long-term potentiation and depression4,5. Another form of molecular memory by CaMKII is formed through the regulated binding to the NMDA-type glutamate receptor subunit GluN2B, which can also generate autonomous activity6. This CaMKII/GluN2B binding is specifically required for maintenance of synaptic strength7 and for normal long-term potentiation but not long-term depression8._ @myers2017CaMKII

_CaMKII Autophosphorylation Is Necessary for Optimal Integration of Ca2+ Signals during LTP Induction, but Not Maintenance. Our findings demonstrate that Thr286 phosphorylation plays an important role in induction of LTP by integrating Ca2+ signals, and it greatly promotes, but is dispensable for, the activation of CaMKII and LTP._ https://www.cell.com/neuron/fulltext/S0896-6273(17)30398-7

As a central signaling protein, CaMKII regulates various cellular functions, including synaptic plasticity, cytoskeletal organization, cell growth and division, gene transcription, and ion channel modulation. 

what do i wanna say here?
Research on CaMKII strongly supports the notion that this enzyme is both necessary and sufficient for the induction of LTP, backed by substantial evidence.

ENTER EVIDENCE of camkii necessry vs sufficient. SUMMARY.https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4050655/ @myers2017CaMKII

--



link in with camkii/nmdar

A rise in calcium lasting less than 2-3 seconds appears to be sufficient to induce LTP, but the magnitude and microdomain location of this signal remain to be reached within consesus for. 

[INSER FIGURE OF DENDRITE AND PSD WITH NMDAR AND AMPARs]

Notably, CaMKII has been extensively proposed to be a key mediator of E-LTP [REFERENCES]. 

During NMDA-receptor dependent LTP, glutamate is released from the presynaptic terminal, which then activates a subtype of glutamate receptor known as the AMPA receptor. NMDA receptors are found nearby these AMPA receptors, but are not activated by low levels of glutamate due to a magnesium ion blocking the pore. If frequent action potentials cause greater stimulation of AMPA receptors, however, this will cause the postsynaptic neuron to depolarize, removing the voltage-dependent magnesium blockage of the NMDA receptor, allowing calcium ions to flow in through the NMDA receptor.

The influx of calcium causes a rise in intracellular calcium concentrations in the postsynaptic density (PSD). The rise of intracellular calcium triggers a cascade of events, including activation of several kinases. Notably, CaMKII has been extensively proposed to be a key mediator of E-LTP [REFERENCES]. 



--

As we have seen, the process of linking cellular mechanisms underlying LTP to learning and memory is often challenging and not always linear. We may feel inclined to infer that one event is a direct consequence of another; however, the mechanisms governing memory formation are intricate and do not always adhere to straightforward cause-and-effect pathways. -> have this sentence. 


For instance, while the work of @morris1986Selective  selectively linking LTP to NMDARs was pivotal in advancing our understanding of the mechanisms underlying memory, it was not without its limitations. One significant limitation was the later realization that NMDA receptors play two roles. While their most widely recognized role involves LTP, NMDARs also play a role in the regulation of synaptic transmission on a moment-to-moment basis, independent of LTP (due to the incomplete Mg²⁺ block at resting potentials). This raised an alternative explanation for Morris' experiments: APV was maybe disrupting hippocampal function more broadly. This caveat was addressed by Giese et al., 1998, who genetically modified a knockin mouse containing the point mutant T286A of CaMKII. This mutation prevents autophosphorylation and blocks CaM-independent persistent activity of the enzyme. In the CaMKII mutant mice subjected to this experiment, NMDA receptor function remained intact, but LTP was absent and learning and memory were strongly impaired. This provided evidence that induced coginitive deficits in rodents were most likely caused by LTP disruption, rather than by general NMDAR dysfunction, as normal NMDA receptor function was maintained throughout the experiment. Taken together, these studies provide compelling evidence for LTP's role in learning and memory.

---
Numerous other kinases and proteins are involved in this complex and intricate mechanism, which has made it challenging to identify all the participating components over the past century. Key players include protein kinase C (PKC), neurogranin, and DAPK1, among others; however, these proteins are beyond the scope of the present project AND discussion of possible interactions 

and protein kinase C (PKC) have been extensively shown to be involved and likely mediate induction of E-LTP [REFERENCES]. In response to a rise in calcium, both kinases can be phosphorylated in an autonomous manner and remain active without the continued presence of calcium. 

where Ca2+ can bind to calmodulin (CaM), and CaM can then aid in CaMKII activation. The activation of CaMKII can allow for various mechanisms of LTP to proceed. CaMKII activity has been shown to be crucial for this form of LTP induction and maintenance, hence, understanding its mechanisms may offer insights into the molecular processes supporting memory stability. As a central signaling protein, CaMKII regulates various cellular functions, including synaptic plasticity, cytoskeletal organization, cell growth and division, gene transcription, and ion channel modulation. 




--
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3102214/ > was reading and good to follow along
https://www.sciencedirect.com/science/article/pii/S0896627316309576 new paper to read > Linking LTP to Learning and Memory
https://www.sciencedirect.com/science/article/pii/B978012374951200007X long-Term Potentiation—A Candidate Cellular Mechanism for Information Storage in the Central Nervous System
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3367554/ > good description of INDUCTION OF LTP AND LTD
--
Early LTP (E-LTP) represents the very first stage of LTP and is a continual form of NMDA receptor-dependent synaptic plasticity. 

While induction entails the transient activation of CaMKII and PKC, maintenance of E-LTP (early-form LTP) is characterized by their persistent activation. It lasts about 30 to 60 minutes, and is independent of protein synthesis

Early LTP represents the foremost stage of LTP and is a continual form of NMDA receptor-dependent synaptic plasticity, and lasts about 30 to 60 minutes. L-LTP, induced by delivery of multiple tetanic stimuli, lasts 5–6 h and requires protein synthesis and gene expression E-LTP, which is evoked by fewer tetanic stimuli and lasts 2–3 h


To this day, LTP has been described at synapses throughout the brain and remains one of the most attractive cellular models for learning and memory. 

--


It is LTP that depends on NMDAR activation where much research has been done [@malenka2004LTPLTDEmbarrassment; @nicoll2017BriefHistoryLongTerm], as it is a well-characterized form of LTP that directly links synaptic activity to molecular signaling pathways crucial for learning and memory. In this project we focus on this type of LTP. During NMDA-receptor dependent LTP, glutamate is released from the presynaptic terminal, which then activates a subtype of glutamate receptor known as the AMPA receptor. NMDA receptors are found nearby these AMPA receptors, but are not activated by low levels of glutamate release because the ion channel of an NMDA receptor is blocked by a magnesium ion. If frequent action potentials cause greater stimulation of AMPA receptors, however, this will cause the postsynaptic neuron to depolarize, which eventually causes the voltage-dependent magnesium blockage of the NMDA receptor to be removed, allowing calcium ions to flow in through the NMDA receptor.

The influx of calcium causes a rise in intracellular calcium concentrations in the postsynaptic density (PSD). The rise of intracellular calcium then triggers a cascade of events, where Ca2+ can bind to calmodulin (CaM), and CaM can then aid in CaMKII activation. The activation of CaMKII can allow for various mechanisms of LTP to proceed. CaMKII activity has been shown to be crucial for this form of LTP induction and maintenance, hence, understanding its mechanisms may offer insights into the molecular processes supporting memory stability. As a central signaling protein, CaMKII regulates various cellular functions, including synaptic plasticity, cytoskeletal organization, cell growth and division, gene transcription, and ion channel modulation. 

An important asset of CaMKII is that it can remain in an active state for prolonged periods of time, even after the initial calcium stimulus is gone. CaMKII can bind to NMDA receptors in the membrane of the cell to enhance its efficiency for receiving new stimuli. CaMKII can also be found bound to the actin filaments which form the cytoskeleton of the neuron. Active CaMKII can unbind from these actin filaments which leads to an expansion in shape of the dendritic spine. This increase in sensitivity to stimuli as well as the expansion of dendritic spines are suggested to allow for synaptic strengthening that happens in LTP.

Importantly, CaMKII and NMDAR binding has been shown to maintain LTP [REFERENCE]; however, the exact mechanisms behind this remain unclear. We don't know how long the CaMKII/NMDAR complex lasts after LTP induction (REFERENCES NEED TO LOOK THIS UP GOOD TO TEST) and more work is also required to elucidate how the CaMKII/NMDAR complex produces the structural growth of the synapse that underlies late LTP. What is more, the precise mechanism of CaMKII and NMDAR interaction to form a complex remains unclear. A longstanding model suggested CaMKII has two distinct sites that bind to the NMDAR C-terminal [REFERENCES]. However, recent crystal structure studies challenge this, showing that CaMKII substrates and activators bind to a single continuous site across the kinase domain [REFERENCE]. The CaMKII/NMDAR complex enables activity-dependent CaMKII incorporation into postsynaptic sites, potentially acting as a structural seed to recruit postsynaptic density proteins, contributing to synapse restructuring and plasticity. 

The specific mechanisms through which the CaMKII/NMDAR complex sustains LTP and facilitates synaptic restructuring remain poorly understood, highlighting the need for further research into their interactions. Understanding these dynamics is important as it may provide insights into the biochemical processes that stabilize memories and contribute to our overall understanding of LTP and memory formation.


### Why use computational modelling to study biological systems

### Reproducibility, Ethics and Data Hazards

This PhD project investigates the temporal and spatial dynamics of NMDA receptor (NMDAR) and calcium/calmodulin-dependent protein kinase II (CaMKII) interactions within the dendritic postsynaptic density. Changes in the function of these synaptic proteins have been implicated in a range of diseases and conditions, including age-related cognitive decline (see, for instance, (Li, Marcu, et al., 2020)) and neurodegenerative diseases (REFERENCES: Reviewed in (Foster, 2007; Tong et al., 2018)). Moreover, these changes have been shown to be implicated in epilepsy, schizophrenia, addiction, autism spectrum condition, and multiple neurodevelopmental disorders (reviewed in (Robison, 2014)).

Additionally, alterations in synaptic strength, like Long-Term Depression (LTD) and Long-Term Potentiation (LTP), involve diverse chemical pathways that have been used to explore the molecular basis of learning and memory [@blundon2008Dissecting]. In particular, studying learning and memory at the molecular level reveals that NMDAR and CaMKII, interacting with other proteins within dendritic spines, play a role in influencing dendritic spines' shape and function [@fink2002Molecular]. Studies using rodents have shown that impairing these molecules interacting, or abolishing their functions leads to memory impairment [@moyano2004NMDA, @zhou2007Interactions, @halt2012CaMKII]. 

Using Monte Carlo algorithm simulations with MCell, BioNetGen and CellBlender, I model molecular interactions. Throughout this PhD project, I identify key factors influencing the efficacy and dynamics of these interactions. These findings contribute to understanding synaptic plasticity mechanisms crucial for memory formation. The biological question that started this PhD was "_How do CaMKII and NMDARs in the postsynaptic neuron interact and enable the processes of learning and memory?_".

As my research progressed, I became increasingly aware of the importance of addressing ethical issues in science, including the biases that persist if not properly examined. Likewise, there is a significant waste of research time and resources that results from conducting experiments that cannot be reliably reproduced or replicated. We might like to think that scientific research is objective, and simply measuring reality. The reality, however, is that many decisions will be taken when doing research, and these decisions will impact the results of that research. If decisions are not well documented, the validity of the research can become more opaque. Similarly, an important issue in scientific work that makes it difficult for other people to build on is that materials or details of analyses are not freely shared, which is why open science is important when overcoming these issues. This awareness has led me to emphasize these issues throughout my work. A key strength of this PhD is its demonstration of how a computational biology project can be reproducible and integrate ethics from the start, as reflected in the Data Hazards aspect of the project.

## Project objectives

I employ computer simulations to answer the project’s biological question; it is important to note that while the focus of this project is mainly computational, this is part of a synergistic work with colleagues performing wet-lab experiments. Experiments provide data to inform simulation parameters, which in turn can guide the wet-lab process by narrowing the experimental search space, in a self-enhancing loop. In short, the main objectives of the project are to:

- Build a computational model of the regulation and interactions between CaMKII and NMDARs in a dendritic spine.
- Make biological predictions from the model which can then be tested experimentally in-vivo or in-vitro.
- Use the model to simulate spatio-temporal dynamics of early LTP and understand the role of CaMKII/NMDAR interactions.
- Develop new workflows to model biological interactions in 3D space, using software like MCell (Monte Carlo Cell) and CellBlender (Stiles et al., 1996; Kerr et al., 2008; Gupta et al., 2018; Husar et al., 2022), BioNetGen (Harris et al., 2016) and BioDynaMo (Breitwieser et al., 2022).

## CaMKII/NMDAR interactions to understand LTP and memory

The cellular changes that underline different forms of memory are thought to involve changes in the strength of neuronal connections; Over a century agp, @ramonycajal1909HistologieSystemeNerveux proposed that the nervous system is composed of microscopic, independent cells —neurons— that form intricate networks of connections. The notion that synaptic strength changes during learning and memory was refined into a concrete model by @hebb1949OrganizationBehaviorNeuropsychological. Hebb proposed that if two neurons are active at the same time, the synapses between them are strengthened. The first mechanism supporting synaptic strengthening, long-term potentiation, was discovered in the early 1970s. The discovery of LTP showed that short, high frequency stimulation (tetanus) of hippocampal excitatory synapses produced a rapid and long-lasting increase in the strength of these synapses that could persist for many days. 

LTP is often divided into three phases: induction, expression, and maintenance. To this day, LTP has been described at synapses throughout the brain and remains one of the most attractive cellular models for learning and memory. 

LTP is considered a key determinant for memory at the molecular level due to the various biochemical and cellular processes that occur at the synaptic level, leading to enduring changes in synaptic strength.

occurs during learning and can last for long periods, making it a probable mechanism for memory storage. Additionally, 

There are multiple forms of LTP. _The variables include the type of synapse, the stimulation parameters, the time analysed after LTP induction, and the developmental age._

It is LTP that depends on NMDAR activation where much research has been done [@malenka2004LTPLTDEmbarrassment; @nicoll2017BriefHistoryLongTerm], as it is a well-characterized form of LTP that directly links synaptic activity to molecular signaling pathways crucial for learning and memory. In this project we focus on this type of LTP. During NMDA-receptor dependent LTP, glutamate is released from the presynaptic terminal, this glutamate then activates a subtype of glutamate receptor known as the AMPA receptor. NMDA receptors are found nearby these AMPA receptors, but are not activated by low levels of glutamate release because the ion channel of an NMDA receptor is blocked by a magnesium ion. If frequent action potentials cause greater stimulation of AMPA receptors, however, this will cause the postsynaptic neuron to depolarize, which eventually causes the voltage-dependent magnesium blockage of the NMDA receptor to be removed, allowing calcium ions to flow in through the NMDA receptor.

The influx of calcium causes a rise in intracellular calcium concentrations in the postsynaptic density (PSD). The rise of intracellular calcium then triggers a cascade of events, where Ca2+ can bind to calmodulin (CaM), and CaM can then aid in CaMKII activation. The activation of CaMKII can allow for various mechanisms of LTP to proceed. CaMKII activity has been shown to be crucial for this form of LTP induction and maintenance, hence, understanding its mechanisms may offer insights into the molecular processes supporting memory stability. As a central signaling protein, CaMKII regulates various cellular functions, including synaptic plasticity, cytoskeletal organization, cell growth and division, gene transcription, and ion channel modulation. 

An important asset of CaMKII is that it can remain in an active state for prolonged periods of time, even after the initial calcium stimulus is gone. CaMKII can bind to NMDA receptors in the membrane of the cell to enhance its efficiency for receiving new stimuli. CaMKII can also be found bound to the actin filaments which form the cytoskeleton of the neuron. Active CaMKII can unbind from these actin filaments which leads to an expansion in shape of the dendritic spine. This increase in sensitivity to stimuli as well as the expansion of dendritic spines are suggested to allow for synaptic strengthening that happens in LTP.

Importantly, CaMKII and NMDAR binding has been shown to maintain LTP [REFERENCE]; however, the exact mechanisms behind this remain unclear. We don't know how long the CaMKII/NMDAR complex lasts after LTP induction (REFERENCES NEED TO LOOK THIS UP GOOD TO TEST) and more work is also required to elucidate how the CaMKII/NMDAR complex produces the structural growth of the synapse that underlies late LTP. What is more, the precise mechanism of CaMKII and NMDAR interaction to form a complex remains unclear. A longstanding model suggested CaMKII has two distinct sites that bind to the NMDAR C-terminal [REFERENCES]. However, recent crystal structure studies challenge this, showing that CaMKII substrates and activators bind to a single continuous site across the kinase domain [REFERENCE]. The CaMKII/NMDAR complex enables activity-dependent CaMKII incorporation into postsynaptic sites, potentially acting as a structural seed to recruit postsynaptic density proteins, contributing to synapse restructuring and plasticity. 

The specific mechanisms through which the CaMKII/NMDAR complex sustains LTP and facilitates synaptic restructuring remain poorly understood, highlighting the need for further research into their interactions. Understanding these dynamics is important as it may provide insights into the biochemical processes that stabilize memories and contribute to our overall understanding of LTP and memory formation.

## Why use computational modelling to study biological systems?

Experimental studies are increasingly complemented by computational models to aid in characterizing the spatiotemporal regulation of proteins of interest [REFERENCES]. Given the complexity and multiscale nature of biological systems, computational models play a crucial role in integrating experimental data, facilitating theoretical hypotheses, and exploring "what if" scenarios. Models aim to make clear the current state of knowledge regarding a particular system, by attempting to be precise about the elements involved and the interactions between them. Doing this can be an effective way to highlight gaps in our understanding and guide future research directions.

Moreover, these models then serve to synthesize knowledge from different published research, and make biological predictions which can then serve as hypothesis to be tested empirically by experimentalists. Additionally, computer-simulated experiments can streamline the wet-lab process by narrowing the experimental search space, making research more cost-effective, time-efficient, and environmentally friendly. This approach also promotes ethical research practices by reducing the need for animal testing, thereby minimizing animal suffering.

## The big picture: What research exists already and where does this PhD stand?

Numerous computational models of CaMKII dynamics have been developed over the past decade to look at different interactions of CaMKII and its substrates or binding partners at varying levels of detail [REFERENCES]. Many of these models center on the binding of calcium to calmodulin and the subsequent formation of the CaM-CaMKII complex [REFERENCES], but not on the CaMKII/NMDAR complex therefore making this research novel in its field. The research carried out in this PhD project follows recent studies [Pharris, Ordyan, Bartol] that have looked at CaMKII as a dodecamer to study its autophosphorylation and spatiotemporal regulation in poststynaptic dendrites using BioNetGen and MCell. Pharris look at this, Ordyan looks at this, Bartol looks at this. This is what I look at.

There is a plethora of computational models with a focus around CaMKII that use software such as NEURON [@maki-marttunen2020Unified], Smoldyn [@khan2011Sequestration], Cellular Dynamic Simulator [@byrne2011Impacts; @byrne2010Cellular], and more [REFERENCES]. While these studies provide a good foundation for understanding CaMKII dynamics, the models either focus solely on temporal dynamics without considering geometry [@maki-marttunen2020Unified], or explore both spatial and temporal dynamics but do not model CaMKII as a multimeric molecule [Pharris, CDS paper]. Some models do account for CaMKII as a multimeric dodecamer but do not focus on its interactions with NMDARs. To my knowledge, this research is novel in the field, as it incorporates all these aspects: modeling CaMKII as a dodecamer, examining spatiotemporal dynamics, and focusing specifically on the CaMKII/NMDAR complex.

Incorporating spatial, temporal, and multimeric aspects is crucial because these dimensions fundamentally shape the behavior of molecular complexes like like the CaMKII/NMDAR interaction. Spatial dynamics can reveal how the molecules interact within different cellular regions, in fact CaMKII phosphorylation levels, as well as its functions have been shown to differ depending on its subcellular localization [@davies2007ACaMKII]. Temporal dynamics are important to understand how CaMKII/NMDAR interactions evolve over time; which is a matter yet to be fully understood, such as: how long does the CaMKII/NMDAR complex last during and/or after LTP?. 

_Needs to go somewhere else not sure where:_ More recently, research is shifting from the long-standing idea that CaMKII behaves like a bistable switch to a new understanding involving a process known as "kinetic proofreading" that enhances the specificity and fidelity of CaMKII-mediated signaling. Bartol et al., 2024 propose that for LTP to occur, the autophosphorylation of CaMKII subunits does not need to reach the high, irreversible steady-state associated with the bistable switch theory. Instead, they propose that the integration of signals at the synapse must lead to a temporary surge in autophosphorylation that is sufficient to initiate one or more downstream processes, which are essentially irreversible, ultimately resulting in synaptic potentiation. This proposed mechanism aligns well with the hypothesis that the CaMKII/NMDAR complex at the PSD plays a critical role in stabilizing CaMKII in its autophosphorylated state, thereby facilitating synaptic potentiation. 

## Main findings of this PhD
To be completed.

## Thesis Layout: This PhD is like a house
To be completed.

As I was thinking about how to layout this thesis, an idea came to me: what if my PhD is like a house, or a hut or something like that? That would help me keep a good picture of the function of each chapter laid out here. So here are some thoughts on how this thesis is laid out; kinda like all thesis are laid out, and like all houses are built, there's common features but each thesis/house comes with the flavour of the person that lives in it.

1. BACKGROUND/PILLARS

If we think of the PhD as a house, then, the pillars or support beams are where I lay out the existing research, the theoretical background, and the context. These are solid and well-researched to support the entire structure, much like how background chapters provide the knowledge necessary to frame ones work. The background chapter in this PhD includes:

* Report style and philosophy
* Open, reproducible and ethical sience definitions
    * Ethics and Reproducibility
        * Science for the profit of whom?
        * Importance of reproducibility
        * Ethics and reproducibility go together
* Software used
    * MCell, BioNetGen, Biodynamo, 
* Different types of modelling used:
    * SSA vs ODE, Rule-based modelling

1. INTRODUCTION/HALL

The main room or entrance is the introduction, it welcomes the guests (readers) and sets the stage. The introduction tells you what you are about to explore: the core ideas, the goals, and what to expect.

* What is this PhD Aabout
* Project objectives
* CaMKII/NMDAR interactions to understand LTP and memory
* Why use computational modelling to study biological systems?
* The big picture: What research exists already and where does this PhD stand?

1. BODY CHAPTERS/ROOMS IN THE HOUSE

* Modelling CaMKII and NMDARs
    * CaMKII structure and functions
    * Modelling CaMKII as a dodecamer
    * NMDARs structure and functions
    * Modelling of NMDARs
    * CaMKII binding to NMDARs

* Data Hazards
    * Work relating to this PhD
    * Applying the labels

* Reproducibility of this project

1. DISCUSSION/ROOF
* TBC

