project:
  type: book

book:
  title: "camkii_thesis"
  author: "Susana Roman Garcia"
  date: now
  date format: long
  chapters:
    - part: index.qmd
      chapters:
      - index.qmd
    - part: 10-intro.qmd
      chapters:
      - 11-philosophy.md
    - part: 20-background.md
      chapters:
      - 21-complex_systems.md
      - 22-reproducibility_open_science.md
      - 23-memory_learning.md
      - 24-why_modelling.md
      - 25-how_we_model.md
    - 30-methods.md
    - 40-results.md
    - references.qmd
  crossref:
    fig-prefix: figure   # (default is "Figure")
    tbl-prefix: table    # (default is "Table")
    ref-hyperlink: false # (default is true)
  downloads: [pdf]
  page-navigation: true

bibliography: 
- references.bib
link-citations: true

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex


