project:
  type: book

book:
  title: "camkii_thesis"
  author: "Susana Roman Garcia"
  date: now
  date format: long
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - background.md
    - methods.md
    - results.md
    - references.qmd
  crossref:
    fig-prefix: figure   # (default is "Figure")
    tbl-prefix: table    # (default is "Table")
    ref-hyperlink: false # (default is true)
  downloads: [pdf]
  page-navigation: true

bibliography: 
- references.bib
link-citations: true

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex


