project:
  type: book

book:
  title: "camkii_thesis"
  author: "Susana Roman Garcia"
  date: now
  date-format: long
  chapters:
    - index.qmd
    - 10-intro.qmd
    - 20-intro-biology.qmd
    - 30-modelling_background.qmd
    - 20-repro_open.qmd
    - 20-data-hazards.qmd
    - 30-model.qmd
    - references.qmd

  downloads: [pdf]
  page-navigation: true

bibliography: 
- references.bib
- methods.bib
- background.bib

link-citations: true
number-depth: 3

format:
  docx:
   toc: true
   number-sections: true
   highlight-style: github   
  html:
    number-sections: true
    theme: pulse
  pdf:
    citeproc: true
    csl: https://www.zotero.org/styles/vancouver-brackets
    toc: true
    number-sections: true
    documentclass: scrreprt
    latex_engine: xelatex
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
        \usepackage{geometry}
        \usepackage{pdfpages}
        \usepackage{afterpage}
    include-after-body: 
      text: |
        \printindex

