project:
  type: book

book:
  title: "CaMKII-NMDAR interactions in Learning and Memory: A Case Study in Ethical and Reproducible Modelling Approaches"
  author: 
    - name: "Susana Román García"
      orcid: "https://orcid.org/0009-0004-6967-7754"
      affiliations:
        - name: "The University of Edinburgh"
          department: "Centre for Discovery Brain Sciences, College of Medicine & Veterinary Medicine, Biomedical Sciences"
  date: now
  date-format: long
  chapters:
    - index.qmd
    - 10-intro.qmd
    - 20-intro-biology.qmd
    - 30-modelling_background.qmd
    - 20-repro_open.qmd
    - 20-data-hazards.qmd
    - 30-model.qmd
    - 40-results.qmd
    - publications.qmd
    - references.qmd

  downloads: [pdf]
  page-navigation: true

bibliography: 
- references.bib
- methods.bib
- background.bib

link-citations: true
number-depth: 3

format:
  docx:
   toc: true
   number-sections: true
   highlight-style: github   
  html:
    number-sections: true
    theme: pulse
  pdf:
    fontsize: 11pt
    template-partials:
      - before-body.tex
    code-block:
      wrap: true
    citeproc: true
    csl: http://www.zotero.org/styles/springer-socpsych-brackets
    toc: false
    lof: false
    number-sections: true
    documentclass: scrreprt
    latex_engine: xelatex
    include-in-header:
      text: |
        \usepackage{typearea}
        \usepackage{makeidx}
        \makeindex
        \usepackage{pdfpages}
        \usepackage{afterpage}
        \usepackage[a4paper, left=2.3cm, right=2.3cm, top=2.3cm, bottom=2.3cm]{geometry}

        \addtokomafont{disposition}{\rmfamily}

    include-after-body: 
      text: |
        \printindex
