project:
  type: book

book:
  title: "camkii_thesis"
  author: "Susana Roman Garcia"
  date: now
  date-format: long
  chapters:
    - index.qmd
    - 10-intro.qmd
    - 20-intro-biology.qmd
    - 20-repro_open.qmd
    - 30-modelling_background.qmd
    - 30-methods.qmd
    - camkii-nmdar-modelling.qmd
    - references.qmd

  downloads: [pdf]
  page-navigation: true
  
bibliography: 
- references.bib
- methods.bib
- background.bib

link-citations: true
number-depth: 1

format:
  docx:
   toc: true
   number-sections: true
   highlight-style: github   
  html:
    number-sections: true
    theme: pulse
  pdf:
    toc: true
    number-sections: true
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex


