# Dedication

# Acknowledgements

“_I want to thank me for believing in me, I want to thank me for doing all this hard work._" - Snoop Dogg. 

Inspired by that quote, I'd like to thank myself for persevering throughout this PhD, and for being patient with myself and this PhD. 

It feels a bit unusual to thank myself but the personal growth I’ve experienced feels significant enough to be recognized here for future reference. I am proud of myself. I can see the differences in my confidence when it comes to coding and my knowledge of what I want and how I want things done. This journey has been one of love, patience, and consistent effort.

I'd like to thank my friend Ceilidh, who has been a refreshing, kind, loving, and solid friendship that I did not expect would happen midway through my PhD. You have been a major support buddy and inspiration to get through this PhD.

I am very grateful for the opportunity to have been an enrichment student at The Alan Turing Institute during the 2022–2023 cohort. It was a catalytic moment for me and for this PhD. My time here really propelled my PhD into what I wanted it to be. The people I met during this time have made a huge impact on my academic and personal life, and I am forever grateful. This experience was also an opening door to the Turing Way Community, whom I would also like to thank as a whole, but particularly some of the people with whom I have had meaningful conversations that have steered the direction of my PhD: Anne Le Steele, Claudia Fischer, Malvika Sharan, and Kirstie Whittaker.

Mention OLS -

The Data Hazards team has also been an amazing group to have been able to interact with, and I'd like to especially thank Natalie Zelenka, Nina Di Cara  and Vanessa Hanschke for their help and support in my Data Hazard endeavours, from co-organising workshops, attending conferences to present this topic to other researchers. 

I'd like to thank my family and particularly my siblings, _Felipe y Clara_, who remind me constantly to take care of myself first, fill up my cup, and, in doing so, show up to anything else with revitalized energy, including this PhD. _Gracias, hermanos amados, os quiero_. My gratitude is extended to James, Florence and Clementine who have put up with a lot of my breakdowns and been there for me all throughout, but especially towards the end of this journey. 

This PhD would have not been possible without the amazing support of my supervisors: Melanie Stefan, David Sterratt and Nicola Romano. I am very lucky that I have had such understanding, caring, supportive and intelligent people as my supervisors; I know I am extremelly privileged to have my PhD under your supervision. You have helped me not only with the content of this thesis, but I feel like you have truly impacted my life in how I want to do research. Your passion and knowledge for doing research with integrity is contagious. Thank you, truly. 

