# Declaration {-}
I declare:

- That the thesis has been composed by myself, and

- that the work is my own, and that if I have been a member of a research group, that I have made a substantial contribution to the work, such contribution is clearly indicated, and 

- that the work has not been submitted for any other degree or professional qualification except as specified, and 

- that any included publications are my own work, except where indicated throughout the thesis and summarised and clearly identified on the declarations page of the thesis. 

```{=latex}
\vspace*{\fill}
\begin{center}
    {\large\bfseries This PhD was supervised by:}
    
    \vspace{2ex}
    
    {\large Dr Nicola Romanò, Dr David C. Sterratt, and Prof Melanie I. Stefan.}
\end{center}
\vfill
```

# Abstract {.unnumbered}

This PhD project integrates biological inquiry with ethical considerations. On the one hand, this PhD investigates the molecular interactions between N-methyl-D-aspartate receptors (NMDARs) and calcium/calmodulin-dependent protein kinase II (CaMKII) in the postsynaptic dendrite during Long-Term Potentiation (LTP), a key process believed to underlie memory formation in animals. Understanding these molecular interactions can provide valuable insights into cognitive function and neurological disorders. Beyond the biological scope, this research also examines how computational models can be employed to study these mechanisms in a way that is both reproducible and ethically responsible. 

A key contribution of this research is the development of a novel computational model that simulates CaMKII as a dodecamer interacting dynamically with NMDARs in both time and space within a neuronal dendrite environment. By doing so, it offers new predictions regarding the role of these molecules in synaptic strengthening and memory-related processes.

Additionally, this project addresses the ethical considerations of such models. Emphasising principles of research integrity, reproducibility, and transparency, this work aligns with FAIR (Findable, Accessible, Interoperable, Reusable) data principles. The model developed in this thesis serves as a case study of how to create a PhD project designed to be open and accessible, ensuring that it can be replicated and extended by future researchers, thereby reducing waste and increasing scientific reliability. In keeping with this approach, this project uses a Data Hazards framework to critically assess potential risks associated with computational modelling, such as environmental impact of the project, how it will be used in the future and what biases it might be perpetuating, implementing strategies to mitigate these risks. By demonstrating how to use this tool, this PhD thesis offers a framework for reducing waste and enhancing scientific reliability across future associated research projects.

Ultimately, this PhD goes beyond the creation of a biological model; it serves as a case study for responsible scientific practice. By integrating molecular neuroscience with ethical research methodologies, this work highlights the importance of both advancing knowledge and conducting science with integrity, ensuring that computational approaches contribute meaningfully to the broader scientific community.

# Lay Summary

This PhD project weaves together multiple threads, including biological questions as well as ethical ones. The foundational thread of this PhD is rooted in a biological question: looking at specific molecular mechanisms underlying learning and memory in animals. Interwoven with this, is the exploration of how these mechanisms can be studied through computer models in a manner that is both reproducible and ethically responsible.

Understanding how learning and memory work at the molecular level can reveal important insights into brain function and potentially help develop treatments for memory-related illnesses. While research in this field often focuses on finding cures, I argue that the true value of this PhD lies not in directly discovering a new mechanism or potential drug, but in providing a project that shows how to create a PhD that upholds research integrity, ensures reproducibility, minimizes waste, and thoughtfully considers broader ethical implications. By prioritizing transparent methodologies, well-documented modelling approaches, and open data practices, this work aims to be easily reused in the future, allowing other researchers to build upon it.

Firstly, to address the biological aspect of this PhD, I begin by explaining why I focus on memory, learning, and the specific molecules involved in these processes. During learning and memory, neural circuits are altered in our brains. These circuits are composed of neurons (nerve cells) that communicate with one another through special junctions called synapses. These synapses contain a pre-synaptic neuron that sends a signal to the post-synaptic neuron. When the travelling signal reaches the end of the presynaptic neuron, it triggers the release of chemical messengers known as neurotransmitters. These chemical messengers cross the synaptic gap and bind to receptors on the postsynaptic neuron, which triggers a cascade of molecular events. This can lead to changes in the strength of synaptic connections. A persistent strengthening of synaptic connections is known as Long Term Potentiation (LTP), which is considered a potential mechanism for explaining learning and memory at the cellular level, where neuronal connections become stronger with repeated activation.

In this cascade of events, I investigate the temporal and spatial dynamics of two molecules in the postsynaptic neuron: N-methyl-D-aspartate receptor (NMDAR) and calcium/calmodulin-dependent protein kinase II (CaMKII). CaMKII and NMDARs are key components of a complex network within neurons that work together to strengthen neuronal connections. 

CaMKII is a complex molecule formed of 12 subunits (dodecamer). Its unique structure allows it to stay active for a long time after an initial signal has passed. CaMKII's capacity to remain active is crucial for strengthening synapses during LTP. Importantly, recent research has shown that the direct interaction between CaMKII and NMDARs might be a minimal requirement for LTP. This means that by focusing on these essential molecular interactions —those between CaMKII and NMDARs— we may be able to isolate some of the essential steps that are eventually leading to memory formation without the added complexity of larger molecular networks.

Moreover, growing evidence suggests that the interaction between NMDARs and CaMKII plays a crucial role at the molecular level in processes related to memory and learning. For example, studies _ab_-using rodents have shown that impairing these molecules interacting, or abolishing their functions leads to memory impairment. Additionally, changes in the function of these molecules have been implicated in a range of diseases and conditions, including age-related cognitive decline in human and non-human animals and neurodegenerative diseases. Likewise, these changes have also been shown to be implicated in epilepsy, schizophrenia, addiction, autism spectrum, and multiple neurodevelopmental disorders.

I use computational models to simulate molecular interactions and investigate these molecular processes. A key innovation in my research is the development of a reproducible computer model that, to the best of my knowledge, is the first to simulate CaMKII as a dodecamer directly interacting with NMDARs in both time and space within a realistic neuronal environment. While previous studies have modelled CaMKII as a dodecamer in a 3D space and over time, they did not explore its direct interactions with NMDARs. This research is valuable because it allows us to make predictions about how CaMKII may interact with NMDARs as essential components for memory mechanisms. 

Given the complexity and multiscale nature of the biological system studied, computational models like the one used in this project play a crucial role in integrating experimental data and theoretical hypotheses. In general, models aim to make clear the current state of knowledge regarding a particular system, by attempting to be precise about the elements involved and the interactions between them. Doing this can be an effective way to highlight gaps in our understanding and guide future research directions. Moreover, these models then serve to synthesize knowledge from different published research, and make biological predictions which can then serve as hypotheses to be tested empirically by experimentalists. Additionally, computer-simulated experiments can streamline the wet-lab process by narrowing the experimental search space, making research more cost-effective, time-efficient, and environmentally friendly. This approach also promotes ethical research practices by reducing the need for animal testing, thereby minimizing animal suffering.

A major emphasis in this PhD is placed on ensuring these models and the techniques used adhere to the principles of reproducibility and FAIR (Findable, Accessible, Interoperable, Reusable) guidelines. This commitment to open, transparent, and ethically responsible research is one of the core strengths of the project. While the PhD centres on creating a biological model of NMDARs and CaMKII, its true value lies in how the model is developed, documented, and made accessible, allowing others to easily build upon it. The model presented in this thesis is reproducible and serves as a case study for how biological models can be developed with careful attention to both scientific integrity and ethical considerations.

Furthermore, I use something known as Data Hazards labels, a framework that highlights the potential risks associated with the research at hand, including topics such as environmental impacts, biases, and misuse of the work at hand. By using Data Hazards, I identify and address key ethical concerns, assigning hazard-like labels (similar to chemical warning labels) to specific risks such as "danger of misuse" or "high environmental impact". This proactive approach allows me to implement and suggest precautions to mitigate potential risks throughout the research process —from design to execution. 

Therefore, this project goes beyond simply creating a model to understand a biological mechanism; this project addresses the pressing issue of how models can be shared and refined in an open, accountable manner, ensuring the research community can rely on them. Ignoring these principles often leads to wasted resources, lost progress, and flawed conclusions—something we cannot afford, especially when working on models that may have real-world implications for areas like memory and neurobiology.

# Acknowledgements

> “_I want to thank me for believing in me, I want to thank me for doing all this hard work._" 
> — Snoop Dogg. 

Inspired by that quote, I'd like to first and foremost thank myself for persevering throughout these four years and a bit, and for being patient with myself and this PhD. It feels a bit unusual to thank myself but the personal growth I’ve experienced feels significant enough to be recognized here for future reference. I am proud of myself. I can see the differences in my confidence when it comes to coding and my knowledge of what I want and how I want things done. This journey has been one of love, patience, and consistent effort.

I'd like to thank my friend Ceilidh, who has been a refreshing, kind, loving, and solid friendship that I did not expect would happen midway through my PhD. You have been a major support buddy and inspiration to get through this PhD.

I'd like to thank my family and particularly my siblings, _Felipe y Clara_, who remind me constantly to take care of myself first, fill up my cup, and, in doing so, show up to anything else with revitalized energy, including this PhD. _Gracias, hermanos amados, os quiero_. My gratitude is extended to James, Florence and Clementine who have put up with a lot of my breakdowns and been there for me all throughout this journey. 

I am very grateful for the opportunity to have been an enrichment student at The Alan Turing Institute during the 2022–2023 cohort. It was a catalytic moment for me and for this PhD. My time here really propelled my PhD into what I wanted it to be. The people I met during this time have made a huge impact on my academic and personal life, and I am forever grateful. This experience was also an opening door to the Turing Way Community, whom I would also like to thank as a whole, but particularly some of the people with whom I have had meaningful conversations that have steered the direction of my PhD: Anne Le Steele, Claudia Fischer, Malvika Sharan, and Kirstie Whittaker.

The Data Hazards team has also been an amazing group to have been able to work with, and I'd like to especially thank Natalie Zelenka and Nina Di Cara for their help and support in my Data Hazard endeavours, from co-organising workshops, and attending conferences to presenting this topic at conferences. In a similar vein, I would also like to thank the team at the Open Seeds Project, as well as the Cohort 6 participants (of which I was a part), for providing the opportunity to deepen my understanding of open science practices.

This PhD would have not been possible without the amazing support of my supervisors: Melanie Stefan, David Sterratt and Nicola Romano. I am very lucky that I have had such understanding, caring, supportive and intelligent people as my supervisors; I know I am extremely privileged to have carried out my PhD under your supervision. Not only have you helped me with the content of this thesis, but I feel like you have truly impacted my life in how I want to do research. Your passion and knowledge for doing research with integrity is contagious. Thank you, truly. 

```{=latex}
\clearpage
{
\hypersetup{linkcolor=black}
\setcounter{tocdepth}{3}
\tableofcontents
\listoffigures
}
```

# Publications and Author Contributions {-}
Chapter 5 includes a published article titled “Data Hazards as an Ethical Toolkit for Neuroscience”, co-authored with Susana Román García, Ceilidh Welsh, Nina H. Di Cara, David C. Sterratt, Nicola Romanò, and Melanie I. Stefan. The article was published in the Journal of Neuroethics on 19 February 2025.

Co-author contributions are detailed in the chapter using Contributor Roles Taxonomy (CRediT) (https://credit.niso.org/). 