## PhD Project Scope
Changes in synaptic strength, like Long-Term Depression (LTD) and Long-Term Potentiation (LTP), involve diverse chemical pathways that have been used to explore the molecular basis of learning and memory [@blundon2008Dissecting]. In particular, studying learning and memory at the molecular level reveals that NMDAR and CaMKII, interacting with other proteins within dendritic spines, play a role in influencing dendritic spines' shape and function [@fink2002Moleculara]. Studies using rodents have shown that impairing these molecules interacting, or abolishing their functions leads to memory impairment [@moyano2004NMDA;@zhou2007Interactionsa;@halt2012CaMKII].

## Software specifications
**MCell4** is a biochemistry simulation tool that uses stochastic Monte Carlo algorithms to simulate movements and interactions of discrete molecules within and between cells, and Brownian motion to model molecule diffusion. This means that 3D spatially realistic models can be created, where volume molecules diffuse, and all molecules within a given radius along its trajectory, or at the point of collision on a surface, are considered for a reaction. A detailed description of mathematical foundations of MCell’s algorithms can be found here: [@bartol2000Monte;@kerr2008Fast;@bartol2015Computational]. Additionally, CellBlender release 4.0 is used as a plug-in for the 3D modelling software Blender 2.93 [@flavell2011Beginning], which provides a graphical user interface for working with and visualizing MCell4 models [@gupta2018Spatiala]. 

**BioNetGen (release 2.8.5)** is a set of software tools that enable a rule-based approach to modelling biochemical reaction kinetics, and can work in combination with MCell modelling. Rule-based modelling represents molecules as structured objects, and then rules are used to define the interactions of these molecules, i.e. molecular interactions are modelled as rules for transforming the attributes of these objects. This use of rules helps to deal with the complexity that can arise from the vast number of protein modifications and complexes generated through protein-protein interactions. BioNetGen Language also allows for site-specific details of protein-protein interactions to be captured in models, which facilitates modelling of holoenzyme structures such as that of CaMKII [@harris2016BioNetGen]. Together, MCell and BioNetGen make it possible to model CaMKII as a dodecamer that interacts with NMDARs and other molecules in a 3D simulation of a dendritic spine.

**BioDynaMo (release 1.04)** is an agent-based modelling tool which can model 3D biophysical molecular interactions [@breitwieser2022BioDynaMo]. In this project, BioDynaMo provides the capability to simulate neuronal growth through formation of an actin cytoskeleton inside dendritic spines, a process with which CaMKII has been shown to be involved with [@okamoto2007Rolea;@zalcman2018CaMKII;@khan2019Architectural]. The model works with actin filaments represented as molecular agents. These can then be modelled to support tree-like structures that can branch out, sever, polymerize and depolymerize in similar manners to the biological equivalent [@trajlinek2022How]. BioDynaMo uses a combination of environment search algorithms [@breitwieser2022BioDynaMo] and data analysis framework such as ROOT [@brun1997ROOT] which allow for simulation of different types of agent diffusion and performing of statistical analysis from simulation data.

for later on RBM

https://academic.oup.com/bioinformatics/article/20/17/3289/186821
https://link.springer.com/protocol/10.1007/978-1-59745-525-1_5

_For example, if the phosphosites of a receptor are lumped together and these sites interact with different adaptor proteins, then lumping may introduce a false competition amongst the adaptor proteins for binding to the receptor. In cases where 1) site-specific details are important, 2) these details entail significant combinatorial complexity, and 3) commonly used simplifications aimed at overcoming the barrier of combinatorial complexity have limited utility or require careful evaluation, what approach should one take to model biomolecular site dynamics?_ https://pmc.ncbi.nlm.nih.gov/articles/PMC3947470/#:~:text=Rule%2Dbased%20models%20are%20compositional,rule%20for%20that%20interaction100.

_A protein with multiple functional components has the potential to interact with multiple binding partners simultaneously. A further layer of complexity arises because a protein may be subject to post-translational modifications at multiple sites46, 47, which regulate interactions and modulate catalytic activities. Many different combinations of interactions and multi-site modifications may be possible, with different combinations contributing to different signaling functions38. This hallmark feature of signaling systems has been termed combinatorial complexity48. The challenges posed by combinatorial complexity, discussed below, motivate the rule-based modeling approach._ https://pmc.ncbi.nlm.nih.gov/articles/PMC3947470/#:~:text=Rule%2Dbased%20models%20are%20compositional,rule%20for%20that%20interaction100.

_. For example, a vertex representing a tyrosine residue in a protein that is a substrate of a protein tyrosine kinase and phosphatase can be associated with the attribute “P” (or “0”) to indicate that the tyrosine is phosphorylated (or unphosphorylated). Accessible formal definitions of the graphs used in rule-based modeling are available114._ https://pmc.ncbi.nlm.nih.gov/articles/PMC3947470/#:~:text=Rule%2Dbased%20models%20are%20compositional,rule%20for%20that%20interaction100.


MAYBE AS SUMMARY FOR BNGL AND MCELL

GOOD PLACE TO LINK TO MCELL? 

In summary, these capabilities make BNGL an ideal language for encoding our models, offering key advantages, BNGL can:

- Facilitate the modelling of domain-specific modifications, which is crucial for understanding site-specific binding and post-translational behaviours in molecules such as CaMKII and NMDA receptors within the postsynaptic density of neuronal dendrites.

- Allow for these interactions to be studied through time and space (when combined with MCell4). This means that we can not only observe site-specific interactions but also track how these interactions evolve over time and within a cellular volume. For instance, we can investigate whether CaMKII is more likely to be phosphorylated near the postsynaptic density or at a distance from it.

-  make models more efficient

--

_Moreover, BioNetGen can be integrated with other modeling tools, such as those for parameter estimation or network analysis, and can be used in combination with experimental data to validate and refine models. Its ability to simulate the dynamics of protein–protein interaction networks in a computationally efficient manner has made it an indispensable tool in computational biology, systems biology, and bioinformatics research._

#### BioNetGen: A Tool for Rule-Based Modeling {.unnumbered}

Moreover, BioNetGen can be integrated with other modeling tools, such as those for parameter estimation or network analysis, and can be used in combination with experimental data to validate and refine models. Its ability to simulate the dynamics of protein–protein interaction networks in a computationally efficient manner has made it an indispensable tool in computational biology, systems biology, and bioinformatics research.

There are three main things that are important here: space, time and structure of molecules (?) -> yes thats why RBM CAN BE HELPFUL. 

the way compratments work in this kind of modelling - will need a methods section that is more specific than this one i think.

what goes in a model and what comes out 


## Reaction Rates (probably not here but later on more specifically)
MCell and BioNetGen use different units for bimolecular kinetic rates. In MCell, a volume-volume reaction (reaction between two molecules that are free to diffuse in 3D space) is M-1*s-1where M is the molar concentration (number of moles per liter). In BioNetGen, the user is not constricted to a specific unit but a usual unit is N-1*s-1where N is a number of molecules per compartment and the default compartment volume if a compartment is not specified is 1fl (= 1 um3).

To convert from BioNetGen to MCell units, one needs to multiply the BioNetGen rate by NA * V where NA is Avogardro’s constant and V is volume of the compartment is liters as derived here:

1/M = 1/(#moles/V) = 1/( (N/NA)/V) = NA * V * 1/N

The unimolecular reaction rates in MCell and BioNetGen both use unit s-1.